//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class meta_location
    {
        public int id { get; set; }
        public string iso { get; set; }
        public string local_name { get; set; }
        public string type { get; set; }
        public Nullable<int> in_location { get; set; }
        public Nullable<decimal> geo_lat { get; set; }
        public Nullable<decimal> geo_lng { get; set; }
        public string db_id { get; set; }
    }
}
