//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentStatus
    {
        public PaymentStatus()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int PaymentStatusID { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
