//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int UserID { get; set; }
        public int ProjectID { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public int PaymentStatus { get; set; }
    
        public virtual PaymentStatus PaymentStatus1 { get; set; }
        public virtual Project Project { get; set; }
    }
}
