//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectStatus
    {
        public ProjectStatus()
        {
            this.Projects = new HashSet<Project>();
        }
    
        public int ProjectStatusID { get; set; }
        public string Status { get; set; }
        public int StatusCode { get; set; }
    
        public virtual ICollection<Project> Projects { get; set; }
    }
}
