//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestNetwork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int ProjectID { get; set; }
        public int AuthorID { get; set; }
        public int LocationCityID { get; set; }
        public string Name { get; set; }
        public int ScopeID { get; set; }
        public string Description { get; set; }
        public string LinkToBusinessPlan { get; set; }
        public string LinkToFinancialPlan { get; set; }
        public string LinkToVideoPresentation { get; set; }
        public string LinkToGuaranteeLetter { get; set; }
        public int ProjectStatusID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Scope Scope { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ProjectStatus ProjectStatus { get; set; }
    }
}
